- platform: miflora
  mac: "C4:7C:8D:66:37:C1"
  name: "Flora1"
  monitored_conditions:
      - temperature
      - battery
      - moisture
      - light
      - conductivity
  #Lutescens
- platform: miflora
  mac: "C4:7C:8D:66:37:C2"
  name: "Flora2"
  monitored_conditions:
      - temperature
      - battery
      - moisture
      - light
      - conductivity  
  #Basilikum
- platform: miflora
  mac: "C4:7C:8D:66:35:7F"
  name: "Flora3"
  monitored_conditions:
      - temperature
      - battery
      - moisture 
      - light
      - conductivity
  #Dracaena Fragrans
- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - temperature
    - hourly_summary
